"""empty message

Revision ID: 0c2fba200fd7
Revises: ce220408982a
Create Date: 2025-06-26 11:32:53.249210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c2fba200fd7'
down_revision = 'ce220408982a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desempenho_atendente_vyrtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desempenho_atendente_vyrtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
