"""empty message

Revision ID: 1cc5cd764f48
Revises: 
Create Date: 2025-06-04 13:56:45.560783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc5cd764f48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fila', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fila', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
