"""empty message

Revision ID: 4d7f6e16a35f
Revises: 6d7b32677311
Create Date: 2025-07-07 10:25:27.368519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7f6e16a35f'
down_revision = '6d7b32677311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restante_p_atendimento', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('restante_s_atendimento', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_column('restante_s_atendimento')
        batch_op.drop_column('restante_p_atendimento')

    # ### end Alembic commands ###
