"""empty message

Revision ID: 594a5a3caf32
Revises: b187a9cb7ccf
Create Date: 2025-06-09 16:00:16.439373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '594a5a3caf32'
down_revision = 'b187a9cb7ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_prioridade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hora_criacao', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('hora_finalizacao', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('data_alteracao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('hora_alteracao', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('chave_usuario', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nome_usuario', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sobrenome_usuario', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nome_completo_solicitante', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('solicitante_email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('sobrenome_operador', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('total_acoes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_anexos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sla', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cod_sub_categoria', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('cod_tipo_ocorrencia', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('cod_categoria_tipo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('cod_status_atual', sa.String(length=10), nullable=True))
        batch_op.drop_column('solicitante')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitante', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('cod_status_atual')
        batch_op.drop_column('cod_categoria_tipo')
        batch_op.drop_column('cod_tipo_ocorrencia')
        batch_op.drop_column('cod_sub_categoria')
        batch_op.drop_column('sla')
        batch_op.drop_column('total_anexos')
        batch_op.drop_column('total_acoes')
        batch_op.drop_column('sobrenome_operador')
        batch_op.drop_column('solicitante_email')
        batch_op.drop_column('nome_completo_solicitante')
        batch_op.drop_column('sobrenome_usuario')
        batch_op.drop_column('nome_usuario')
        batch_op.drop_column('chave_usuario')
        batch_op.drop_column('descricao')
        batch_op.drop_column('hora_alteracao')
        batch_op.drop_column('data_alteracao')
        batch_op.drop_column('hora_finalizacao')
        batch_op.drop_column('hora_criacao')
        batch_op.drop_column('nome_prioridade')

    # ### end Alembic commands ###
