"""empty message

Revision ID: 6d7b32677311
Revises: 793c4def7fd6
Create Date: 2025-07-03 14:59:38.481102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7b32677311'
down_revision = '793c4def7fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_importacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_column('data_importacao')

    # ### end Alembic commands ###
