"""empty message

Revision ID: 793c4def7fd6
Revises: e8f2e809ae0b
Create Date: 2025-07-01 11:10:22.165054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793c4def7fd6'
down_revision = 'e8f2e809ae0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_importacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_colaboradores', schema=None) as batch_op:
        batch_op.drop_column('data_importacao')

    # ### end Alembic commands ###
