"""empty message

Revision ID: ce220408982a
Revises: f513e793d2fc
Create Date: 2025-06-24 14:27:44.331044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce220408982a'
down_revision = 'f513e793d2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_atendimento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sla_resolucao', sa.String(length=100), nullable=True))
        batch_op.drop_column('sla')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('sla_resolucao')
        batch_op.drop_column('sla_atendimento')

    # ### end Alembic commands ###
