"""empty message

Revision ID: e8f2e809ae0b
Revises: 0c2fba200fd7
Create Date: 2025-06-26 11:34:08.740256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8f2e809ae0b'
down_revision = '0c2fba200fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desempenho_atendente_vyrtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operador_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ch_atendidas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ch_naoatendidas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_livre', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pimprod_refeicao', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_minatend', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_medatend', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tempo_maxatend', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('data',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_desempenho_atendente_vyrtos_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_desempenho_atendente_vyrtos_operador_id'), ['operador_id'], unique=False)
        batch_op.drop_column('tempo_totalatend')
        batch_op.drop_column('chamadas_atendidas')
        batch_op.drop_column('data_importacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desempenho_atendente_vyrtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_importacao', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('chamadas_atendidas', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tempo_totalatend', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_desempenho_atendente_vyrtos_operador_id'))
        batch_op.drop_index(batch_op.f('ix_desempenho_atendente_vyrtos_data'))
        batch_op.alter_column('data',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('tempo_maxatend')
        batch_op.drop_column('tempo_medatend')
        batch_op.drop_column('tempo_minatend')
        batch_op.drop_column('pimprod_refeicao')
        batch_op.drop_column('tempo_livre')
        batch_op.drop_column('ch_naoatendidas')
        batch_op.drop_column('ch_atendidas')
        batch_op.drop_column('operador_id')

    # ### end Alembic commands ###
