"""empty message

Revision ID: f513e793d2fc
Revises: f649d631aa7d
Create Date: 2025-06-24 10:23:20.077742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f513e793d2fc'
down_revision = 'f649d631aa7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_colaboradores', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
