"""empty message

Revision ID: f649d631aa7d
Revises: 594a5a3caf32
Create Date: 2025-06-11 09:13:40.665197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f649d631aa7d'
down_revision = '594a5a3caf32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_vinculo', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_column('tipo_vinculo')

    # ### end Alembic commands ###
